{{- $retrain := index .Values.services "retrain" -}}
{{- if and $retrain.persistence $retrain.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "zerocraftr-ai.fullname" . }}-registry
  labels:
    {{ include "zerocraftr-ai.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $retrain.persistence.size }}
  {{- if $retrain.persistence.storageClassName }}
  storageClassName: {{ $retrain.persistence.storageClassName }}
  {{- end }}
{{- end }}
