apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerocraftr-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zerocraftr-ml
  template:
    metadata:
      labels:
        app: zerocraftr-ml
    spec:
      containers:
      - name: ml
        image: zerocraftr/ml-system:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: zerocraftr-ml
spec:
  selector:
    app: zerocraftr-ml
  ports:
  - port: 5000
    targetPort: 5000
